name: Build Code-Server Environment Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: '镜像标签（例如：v1.0.0）'
        required: true
        default: 'latest'
      push_to_registry:
        description: '是否推送到Docker Hub'
        required: true
        type: choice
        options:
          - 'false'
          - 'true'
        default: 'false'

env:
  IMAGE_NAME: imzh2077/code-server-with-env
  TARGET_PLATFORM: 'linux/arm64'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64

      - name: Log in to Docker Hub (可选)
        if: github.event.inputs.push_to_registry == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.TARGET_PLATFORM }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.event.inputs.image_tag }}
            ${{ env.IMAGE_NAME }}:latest
          push: ${{ github.event.inputs.push_to_registry == 'true' }}
          outputs: type=docker,dest=/tmp/image.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save image as artifact
        if: github.event.inputs.push_to_registry == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: /tmp/image.tar
          retention-days: 1

      - name: Display image info
        run: |
          echo "镜像构建完成！"
          echo "镜像名称: ${{ env.IMAGE_NAME }}"
          echo "镜像标签: ${{ github.event.inputs.image_tag }}"
          echo "目标平台: ${{ env.TARGET_PLATFORM }}"
          if [ "${{ github.event.inputs.push_to_registry }}" = "true" ]; then
            echo "已推送到 Docker Hub"
          else
            echo "镜像已保存为工作流产物，可在 Artifacts 中下载"
          fi
